"""
TDD Tests: Hybrid RAG AI Search Engine (Chunker, BM25 + Vector Retrieval, RRF Fusion, Reranking, Grounded Generation).
"""

import os
import pytest


def test_semantic_document_chunker(valid_article_payload):
    """Verify semantic document chunker splits text while preserving all required document metadata."""
    from src.rag.chunker import SemanticChunker

    chunker = SemanticChunker(chunk_size=100, chunk_overlap=20)
    
    # Long article content
    article = valid_article_payload.copy()
    article["content"] = (
        "Modern Data Engineering requires building robust data pipelines that clean, transform, and quality-gate raw data. "
        "Delta Lake provides ACID transaction capabilities on top of cloud object storage. "
        "Retrieval-Augmented Generation (RAG) integrates vector store search with Large Language Models to answer user queries with verifiable sources. "
        "Reciprocal Rank Fusion combines vector embeddings with BM25 keyword matching for optimal search relevance."
    )

    chunks = chunker.chunk_article(article)
    assert len(chunks) > 1

    first_chunk = chunks[0]
    assert "article_id" in first_chunk
    assert first_chunk["article_id"] == article["article_id"]
    assert "chunk_id" in first_chunk
    assert "category" in first_chunk
    assert first_chunk["category"] == article["category"]
    assert "text" in first_chunk
    assert len(first_chunk["text"]) > 0


def test_rrf_reciprocal_rank_fusion_math():
    """Verify that Reciprocal Rank Fusion (RRF) correctly merges dense vector and BM25 rank lists."""
    from src.rag.hybrid_search import compute_rrf_scores

    # Document list 1 (Vector rank order: DocA, DocB, DocC)
    dense_ranks = ["doc_a", "doc_b", "doc_c"]
    
    # Document list 2 (BM25 rank order: DocB, DocA, DocD)
    sparse_ranks = ["doc_b", "doc_a", "doc_d"]

    # Compute RRF with k=60
    # doc_a: 1/(60+1) + 1/(60+2) = 0.01639 + 0.016129 = 0.032519
    # doc_b: 1/(60+2) + 1/(60+1) = 0.016129 + 0.01639 = 0.032519
    # doc_c: 1/(60+3) = 0.015873
    # doc_d: 1/(60+3) = 0.015873
    fused_results = compute_rrf_scores(dense_ranks, sparse_ranks, k=60)
    
    assert len(fused_results) == 4
    top_doc_ids = [item["doc_id"] for item in fused_results]
    assert "doc_a" in top_doc_ids[:2]
    assert "doc_b" in top_doc_ids[:2]
    assert fused_results[0]["rrf_score"] > fused_results[2]["rrf_score"]


def test_hybrid_search_retrieval(temp_workspace):
    """Verify HybridSearch retrieves top documents using both lexical BM25 and dense vector store."""
    from src.rag.hybrid_search import HybridSearchEngine

    db_dir = os.path.join(temp_workspace, "chromadb_test")
    engine = HybridSearchEngine(persist_directory=db_dir)

    sample_chunks = [
        {
            "chunk_id": "chunk_01",
            "article_id": "art_100",
            "title": "Apache Spark Delta Lake Deep Dive",
            "category": "Data_Engineering",
            "text": "Delta Lake brings ACID transactions and time travel capabilities to Apache Spark workloads."
        },
        {
            "chunk_id": "chunk_02",
            "article_id": "art_200",
            "title": "Vector Databases and Embeddings",
            "category": "AI_ML",
            "text": "ChromaDB stores high-dimensional vector embeddings generated by sentence transformer models."
        },
        {
            "chunk_id": "chunk_03",
            "article_id": "art_300",
            "title": "Kafka Real-Time Ingestion",
            "category": "Data_Engineering",
            "text": "Confluent Kafka streams continuous raw events with Pydantic validation into Dead-Letter Topics."
        }
    ]

    engine.index_chunks(sample_chunks)

    # Search for vector embeddings query
    query = "How do vector databases store embeddings?"
    results = engine.search(query=query, top_k=2)

    assert len(results) > 0
    top_hit = results[0]
    assert top_hit["article_id"] == "art_200"
    assert "rrf_score" in top_hit


def test_cross_encoder_reranker():
    """Verify Cross-Encoder reranker updates document ordering based on query context relevance."""
    from src.rag.reranker import DocumentReranker

    reranker = DocumentReranker()

    query = "ACID transactions in PySpark"
    candidates = [
        {"doc_id": "c1", "text": "Confluent Kafka streams real time events to topics."},
        {"doc_id": "c2", "text": "Delta Lake provides full ACID transactions and MERGE capabilities in PySpark."},
        {"doc_id": "c3", "text": "Airflow orchestrates DAG task execution schedules."}
    ]

    reranked = reranker.rerank(query=query, candidates=candidates, top_n=2)
    assert len(reranked) == 2
    assert reranked[0]["doc_id"] == "c2"
    assert "rerank_score" in reranked[0]


def test_rag_engine_grounded_answer_generation():
    """Verify Grounded RAG engine outputs answers with explicit inline citations matching format [Article ID: X, Chunk: Y]."""
    from src.rag.rag_engine import RAGEngine

    rag_engine = RAGEngine(use_mock_llm=True)

    query = "What technology provides ACID transactions in PySpark?"
    context_chunks = [
        {
            "article_id": "art_100",
            "chunk_id": "chunk_01",
            "title": "Delta Lake Architecture",
            "text": "Delta Lake brings ACID transaction support and schema enforcement to PySpark DataFrames."
        }
    ]

    response = rag_engine.generate_grounded_response(query=query, context_chunks=context_chunks)

    assert "answer" in response
    assert "citations" in response
    assert len(response["citations"]) > 0
    
    # Verify citation format matching requirement
    first_citation = response["citations"][0]
    assert "article_id" in first_citation
    assert "chunk_id" in first_citation
    assert "art_100" in response["answer"] or "[Article ID: art_100, Chunk: chunk_01]" in response["answer"]
